on: workflow_dispatch

name: Deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        env:
          TF_VERSION: 1.2.5
        run: |
          curl -LO https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
          sudo unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin
      - name: Deploy Infrastructure with Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          TF_VAR_image: 808944423154.dkr.ecr.us-east-1.amazonaws.com/devopsdemo123
        run: |
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          cd terraform
          terraform init -backend-config=key=$BRANCH_NAME
          terraform apply -auto-approve -var environment=$BRANCH_NAME
